[project]
name = "movieApp"
version = "1.0.0"
description = "My app for tracking movies"
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
